apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-410007

  artifacts:
    - image: us.gcr.io/ticketing-410007/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-410007/client
      context: client
      docker:

        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .

    - image: us.gcr.io/ticketing-410007/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
